# client-app/pubspec.yaml
name: client_app
description: "Client-facing app for Centro de Apoyo para la Familia."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

# Application Dependencies
dependencies:
  flutter:
    sdk: flutter
  
  # For making HTTP requests to our Go API.
  http: ^1.2.1
  
  # For securely storing the JWT on the device after login.
  flutter_secure_storage: ^9.0.0
  
  # A simple state management and dependency injection provider.
  provider: ^6.1.2
  web_socket_channel: ^2.4.5
  url_launcher: ^6.3.1
  app_links: ^6.4.0
  path_provider: ^2.1.5
  open_filex: ^4.7.0

  cupertino_icons: ^1.0.6

# Development-only Dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4

# Flutter-specific configuration
flutter:
  uses-material-design: true
  assets:
    - mobile-app-icon.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: mobile-app-icon.png
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: mobile-app-icon.png
